### ISSUE TITLE
TOML doesn't participate in view provider SingleRootFileViewProvider

### ISSUE THREAD

**Issue by elennaro** [intellij-rust/intellij-toml#6]
The error:

```
Language Language: TOML doesn't participate in view provider SingleRootFileViewProvider{myVirtualFile=file:///home/me/project/Cargo.toml, content=VirtualFileContent{size=210}}: [Language: TOML]
```

The stacktrace:

```
Language Language: TOML doesn't participate in view provider SingleRootFileViewProvider{myVirtualFile=file:///home/me/project/Cargo.toml, content=VirtualFileContent{size=210}}: [Language: TOML]
java.lang.AssertionError: Language Language: TOML doesn't participate in view provider SingleRootFileViewProvider{myVirtualFile=file:///home/me/project/Cargo.toml, content=VirtualFileContent{size=210}}: [Language: TOML]
    at com.intellij.extapi.psi.PsiFileBase.a(PsiFileBase.java:58)
    at com.intellij.extapi.psi.PsiFileBase.<init>(PsiFileBase.java:40)
    at org.toml.lang.core.psi.TomlFile.<init>(TomlFile.kt:9)
    at org.toml.lang.core.parser.TomlParserDefinition.createFile(TomlParserDefinition.kt:24)
    at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:403)
    at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:344)
    at com.intellij.psi.SingleRootFileViewProvider.b(SingleRootFileViewProvider.java:322)
    at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:167)
    at com.intellij.psi.SingleRootFileViewProvider.getPsi(SingleRootFileViewProvider.java:151)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:401)
    at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:184)
    at com.intellij.psi.impl.file.PsiDirectoryImpl.processChildren(PsiDirectoryImpl.java:197)
    at com.intellij.ide.projectView.impl.nodes.ProjectViewDirectoryHelper.a(ProjectViewDirectoryHelper.java:204)
    at com.intellij.ide.projectView.impl.nodes.ProjectViewDirectoryHelper.getDirectoryChildren(ProjectViewDirectoryHelper.java:154)
    at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.getChildrenImpl(PsiDirectoryNode.java:143)
    at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.getChildren(AbstractPsiBasedNode.java:89)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:47)
    at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1620)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1617)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$4800(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1542)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1529)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1252)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$3200(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1175)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1172)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1167)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1073)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:500)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:496)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:355)
    at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:118)
    at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4833)
    at javax.swing.JTree.fireTreeExpanded(JTree.java:2775)
    at javax.swing.JTree.setExpandedState(JTree.java:3629)
    at javax.swing.JTree.expandPath(JTree.java:2212)
    at com.intellij.ide.util.treeView.AbstractTreeUi$55.perform(AbstractTreeUi.java:3289)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3310)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3278)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1509)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1476)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4493)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4429)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8800(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$76.perform(AbstractTreeUi.java:4307)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4321)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8900(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$75.perform(AbstractTreeUi.java:4267)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4241)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4231)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4226)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4222)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expand(AbstractTreeBuilder.java:135)
    at com.intellij.ide.util.treeView.TreeState$BuilderFacade.expand(TreeState.java:486)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.applyExpanded(TreeState.java:274)
    at com.intellij.ide.util.treeView.TreeState.access$200(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$1$1.run(TreeState.java:287)
    at com.intellij.ide.util.treeView.AbstractTreeUi.batch(AbstractTreeUi.java:2496)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.batch(AbstractTreeBuilder.java:529)
    at com.intellij.ide.util.treeView.TreeState$BuilderFacade.batch(TreeState.java:472)
    at com.intellij.ide.util.treeView.TreeState$1.perform(TreeState.java:284)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
    at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
    at com.intellij.openapi.util.BusyObject$Impl.onReady(BusyObject.java:54)
    at com.intellij.openapi.util.BusyObject$Impl.onReady(BusyObject.java:39)
    at com.intellij.ide.util.treeView.AbstractTreeUi.maybeReady(AbstractTreeUi.java:2149)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processNodeActionsIfReady(AbstractTreeUi.java:2864)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4497)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4429)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8800(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$76.perform(AbstractTreeUi.java:4307)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4321)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8900(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$75.perform(AbstractTreeUi.java:4267)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4241)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4231)
    at com.intellij.ide.util.treeView.UpdaterTreeState$1$2.perform(UpdaterTreeState.java:191)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.UpdaterTreeState$1.perform(UpdaterTreeState.java:188)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
    at com.intellij.ide.util.treeView.AbstractTreeUi._select(AbstractTreeUi.java:3795)
    at com.intellij.ide.util.treeView.AbstractTreeUi._select(AbstractTreeUi.java:3765)
    at com.intellij.ide.util.treeView.UpdaterTreeState.restore(UpdaterTreeState.java:175)
    at com.intellij.ide.util.treeView.AbstractTreeUi.maybeReady(AbstractTreeUi.java:2129)
    at com.intellij.ide.util.treeView.AbstractTreeUi.removeLoading(AbstractTreeUi.java:2824)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$3900(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$30$2$1$1.onReady(AbstractTreeUi.java:1420)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processActions(AbstractTreeUi.java:2881)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processNodeActionsIfReady(AbstractTreeUi.java:2848)
    at com.intellij.ide.util.treeView.AbstractTreeUi.flushPendingNodeActions(AbstractTreeUi.java:2172)
    at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYeildingFinished(AbstractTreeUi.java:2108)
    at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2096)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$6000(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.perform(AbstractTreeUi.java:1984)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2187)
    at com.intellij.ide.util.treeView.AbstractTreeUi$37.perform(AbstractTreeUi.java:1979)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
    at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
    at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
    at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The Cargo.toml

```
[package]
name = "project"
version = "0.1.0"
authors = ["Alexander Art <a@a.com>"]

[dependencies]
csv = "0.14"
rustc-serialize = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
```

Also the Cargo.toml is not visible in Project (Idea on linux).

**Comment by matklad** [comment]
This looks bad, but unfortunately I can't reproduce the error. Can you give a bit more details?

Is it correct that you have both Rust and Toml plugins installed?
Does the error happen all the time? 
How did you open the project (`import from sources` vs plain `open`)?

And any other details will be useful, I don't quite understand what may be causing this.

**Comment by elennaro** [comment]
1. I have both plugin installed.
2. The error happens all the time I open the project.
3. The project was imported from sources, after `cargo new project --bin`.

It has all the files in git. It was generated on windows. Then moved by copy-paste to linux ( :) ). Nothing special there.
